matchID-project/backend

- code/recipe.py
- better support for fwf files (encodings)
- default csv separator to ';'
- internal_eval supports now multiline for python formulas (and still full python code)
- refactoring in internal_rename
> Fwf encoding support & mixed minor changes

- code/recipe.py
- conf/connectors/connectors.yml
- conf/recipes/date.yml
- conf/recipes/name.yml
- referential_data/2017_communes_alg_norm.csv
- added a stacking method for datasets, enabling multi-files selection by regex
- updated inmemory caching method, which was buggy (previously cached filtered version, now caches both full dataset and filtered versions, and decorrelates automata creation caches)
- added geopoints for Arrondissements for Paris/Lyon/Marseille and Oran/Alger/Constantine
- bug fixes in fwf/csv read/write (encoding and header bugs)
> Stacking files, inmemory join caching, ref datasets and bug fixes

- code/recipe.py
- conf/recipes/location.yml
- conf/recipes/matching.yml
- datasets : bug fix in csv with columns names with trailing space
- internal_recipes : bug fix in fuzzy match : first match 0-dist then 1 then 2
- packaged recipes : better location prep for Paris/Lyon/Marseille and stop words
- packaged recipes : better location scoring (differentiated scoring for FRA vs out ouf FRA)
- packaged recipes : bug fix in diff for src field
> recipes: better location prep, scoring, and bug fix in fuzzy match

- code/recipe.py
- dataset : bug fix for csv header with trailing space : tested on a full run
> Patch csv columns trailing space

- Dockerfile_elasticsearch_phonetic
- code/recipe.py
- nginx.conf
api:
- change jobs format (for easier parsing in the frontend)
- update conf reading in both recipe and datasets
- returns explanation of error when something wrong in reading dataset
- reject bad formed yaml BEFORE saving it (!)
recipes : 
- added a first grouby draft
- tuples <> list conversion
nginx: 
- integrated kibana in main path
> Api changes (jobs) & minor updates

- code/recipe.py
- conf/recipes/location.yml
- nginx.conf
- internals: nest, ngrams, groupby
- bug fix in join
- nginx better kibana support
> Multiple recipes enhancement

- code/recipe.py
Better logs : 
- "Ooops" message factorization
- time since beginning of the recipe
- chunk number on each line (=> better error tracability)
- number of errors at the end of the run
Automation: added "before", "run" and "after" to run other recipes before & after
> Logs enhancement & automation

- code/recipe.py
- elasticsearch timeout increase
- betters stats in logs at the end of the recipe
> Jobs automation

- code/recipe.py
- conf/recipes/location.yml
- included recipes : reverse patch of citycode_history linked to the json.loads broadcast problem
- elasticsearch score of each match included
- elasticsearch retry on insert
> ES score & more

- code/recipe.py
- conf/recipes/location.yml
- conf/recipes/matching.yml
- migration to jellyfish levenshtein (very low optim 0.4% times faster)
- refacto of scoring for better performance benchmark
- bug fix in french city normalization
> Levenshtein optim / scoring

- code/recipe.py
- conf/recipes/name.yml
- api:
- validation : now overridable within dataset
- search : first draft of api, clone of validation
- dataset : added the type on-the-fly (elasticsearch or filesystem)
- bug fixes:
- recipes names.yml : corrected unordering of first names
- prefix in es join was missing for columns total and max_score
> Api minor evol & bug fixes

- code/recipe.py
using custom parallel queue instead parallel_bulk of elasticsearch python lib for better control
> parallel writes

- code/recipe.py
- added a supervisor to mesure length of queues and optimizing to avoid performance errors in injection or suboptimization of cpu usage
> Thread queues (compute/writing) supervision

- code/recipe.py
- better job stop
- elasticsearch : more configurable (safe, max_tries)
> More robust threads

- Dockerfile
- code/api.py
- code/config.py
- code/log.py
- code/recipes.py
- code/tools.py
First 99% functionnal refacto (tested on deaths/clients usecase) (only remaining non functionnal : chainable recipes)
> first refacto: splitted recipe into : api, recipes, tools, log

- code/api.py
- code/recipes.py
- conf/conf.yml
New bug was linked to refactoring
> Refacto - validation api debug

- .gitignore
- Dockerfile
- code/api.py
- code/recipes.py
- conf/connectors/connectors.yml
- docker-compose-dev.yml
read/write support to SQL - tested with postgres - import should further support parsing of json objects (list, dict)
> added SQLalchemy and tested support for postgres (I/O)

- code/recipes.py
for memory limitation in analytic operations (groupby, clique, ..)
> filtering input dataset

- Makefile
- code/api.py
- code/config.py
- code/recipes.py
- docker-components/Dockerfile_elasticsearch_phonetic
- docker-components/docker-compose-elasticsearch-phonetic.yml
- nginx/nginx-run.conf
+ misc updates : make simplified, elasticsearch 6.1.2 update
> Jobs supervising : now support recursive calls ("scenarios")

- code/api.py
- code/recipes.py
allow random_view: false in dataset
> elasticsearch fixed vs random_view

- code/api.py
- code/recipes.py
enable the possiblility to view randomly the data or not in es dataset with random_view: true (default) or random_view: false
> elasticsearch dataset random_view false or true

- Makefile
- code/tools.py
- docker-components/Dockerfile_elasticsearch_phonetic
- docker-components/docker-compose-elasticsearch-node.yml
- docker-components/docker-compose-elasticsearch.yml
- removed mem_limit for elasticsearch as buggy
- renamed dev
- added update
- migration to elasticsearch 6.2.2
- tools : added random library (regression fix)
> Automation update + added random library to tools (for being available in eval)

- Makefile
- code/api.py
- code/parsers.py
- code/recipes.py
- docker-components/docker-compose-dev-frontend.yml
- docker-components/docker-compose-run-frontend.yml
- nginx/gzip.conf
- Api/datasets: elasticsearch proxy for dataset search
- recipes.py PEP8 linting
- nginx added gzip for performance
- Automation / make bug fix for dev
> Mixed things

- .gitignore
- Makefile
- nginx/nginx-run.conf
support for a "artifact" file where your can override ES_NODES & PORT & more
> Artifacts externalization

- Makefile
- code/api.py
- code/recipes.py
bug fixes: 
- jobs
- more explicit usage of regex in table names
automation:
- added local docker-compose usage for customizing without forking
> Lint, bug fixes and automation

- Dockerfile
- Makefile
- code/api.py
- code/config.py
- code/parsers.py
- code/recipes.py
- code/security.py
- conf/conf.yml
- conf/security/default.yml
- creds.yml
> First login api (simple auth) and minor api evol

- Dockerfile
- code/api.py
- code/recipes.py
- conf/conf.yml
Server Side Events have been implemented to reduce api calls when running recipe and looking at logs
> SSE streaming logs

- Dockerfile
- Makefile
- code/api.py
- conf/conf.yml
- docker-compose-dev.yml
- docker-compose.yml
…od), and make api path configurable
> separate dev and prod for backend Docker fix #172

- aws
> aws wrapping ebug

- .travis.yml
- requirements.txt
fix werkzeug to 0.16.1 as proposed in https://github.com/noirbizarre/flask-restplus/issues/777
> breaking change with werkzeug and flaskrestplus

- code/recipes.py
py2 to py3 csv writing (wb to w)
> fix writing csv
